import Head from 'next/head';
import { AppProps } from 'next/dist/next-server/lib/router/router';
import '../styles/globals.css';

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
	const {counter, title} = pageProps;
	const demo = [];

	
  return (
    <>
      <Head>
        <title>Rate App</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
			{

			}
			{/* <button onClick={} /> */}
      <Component {...pageProps} />
    </>
  );
}

const pageProps = {
	counter: 1,
	title: '',
};

export default MyApp;
