import { AppProps } from 'next/dist/shared/lib/router/router'
import Head from 'next/head'
import ym, { YMInitializer } from 'react-yandex-metrika'
import '../styles/globals.css'

function MyApp({ Component, pageProps, router }: AppProps): JSX.Element {
	router.events.on('routeChangeComplete', url => {
		if (typeof window !== 'undefined') {
			ym('hit', url)
		}
	})
	return (
		<>
			<Head>
				<title>Rate App</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' />
				<link rel='preconnect' href='https://mc.yandex.ru' />
				<link
					href='https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap'
					rel='stylesheet'
				/>
				<meta name='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
				<meta name='og:locale' content='ru_RU' />
			</Head>
			<YMInitializer accounts={[]} options={{ webvisor: true, defer: true }} version='2' />
			<Component {...pageProps} />
		</>
	)
}

const pageProps = {
	counter: 1,
	title: '',
}

export default MyApp
